### ISSUE TITLE
Dynamically updated output with `run`

### ISSUE THREAD

**Issue by Hong-Revo** [r-lib/processx#229] opened 2019-11-21 23:59 UTC
It would be nice if `run` had better support for programs that continually update the screen. Taking the example of docker again:

- `system2("docker", "pull <foo>")` prints the status updates to the screen as they occur, with progress bars that update properly. It mimics what you'd see if you ran docker from the commandline.
- `processx::run("docker", c("pull", "<foo>"), echo=TRUE)` doesn't show the progress bars at all, and only shows the updated status as each layer operation completes.

**Comment by gaborcsardi** [comment] 2019-11-22 00:07
This is essentially a duplicate of #72.

Also, it is up to docker to decide what it outputs. For the processx case, seeing that stdout / stderr are pipes, it decides not to output progress bars.

On Unix we might be able to fix this issue via pseudo terminals, which processx already supports

**Comment by Hong-Revo** [comment] 2019-11-22 00:11
Oh, seeing the mention of pseudo-terminals reminded me of https://github.com/Microsoft/Terminal

Maybe also worth looking into supporting this on Win 10?

**Comment by gaborcsardi** [comment] 2019-11-22 00:12
Yeah, we could support them on Win 10.

Also, `run()` needs to support them as well, currently only `process` has them, I'll open some issues.

**Comment by gaborcsardi** [comment] 2020-02-11 11:44
There are issues for pty support in `run()` and on Windows, so I am going to close this now.

**Closed by gaborcsardi** 2020-02-11 11:44 UTC
