### ISSUE TITLE
Cannot install github version - fatal error: Rinternals.h: No such file or directory

### ISSUE THREAD

**Issue by trafficonese** [r-lib/processx#257] opened 2020-06-05 06:50 UTC
When running `remotes::install_github("r-lib/processx")` I see the following error

> errors.h:15:24: fatal error: Rinternals.h: No such file or directory
>  #include <Rinternals.h>
>                         ^
> compilation terminated.

<details><summary>session info</summary>
<p>

```
- Session info ----------------------------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.6.1 (2019-07-05)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  German_Germany.1252         
 ctype    German_Germany.1252         
 tz       Europe/Berlin               
 date     2020-06-05                  

- Packages --------------------------------------------------------------------------------------------------------------------------------------------------
 package      * version    date       lib source                           
 assertthat     0.2.1      2019-03-21 [1] CRAN (R 3.5.3)                   
 bit            1.1-15.2   2020-02-10 [1] CRAN (R 3.6.2)                   
 bit64          0.9-7      2017-05-08 [1] CRAN (R 3.5.0)                   
 blob           1.2.1.9000 2020-03-17 [1] Github (tidyverse/blob@0e63151)  
 class          7.3-15     2019-01-01 [1] CRAN (R 3.6.1)                   
 classInt       0.4-2      2019-10-17 [1] CRAN (R 3.6.1)                   
 cli            2.0.2      2020-02-28 [1] CRAN (R 3.6.3)                   
 colorspace     1.4-1      2019-03-18 [1] CRAN (R 3.5.3)                   
 config         0.3        2018-03-27 [1] CRAN (R 3.5.2)                   
 crayon         1.3.4      2017-09-16 [1] CRAN (R 3.5.1)                   
 crosstalk      1.1.0.1    2020-03-13 [1] CRAN (R 3.6.3)                   
 curl           4.3        2019-12-02 [1] CRAN (R 3.6.1)                   
 data.table     1.12.8     2019-12-09 [1] CRAN (R 3.6.1)                   
 DBI            1.1.0      2019-12-15 [1] CRAN (R 3.6.2)                   
 digest         0.6.25     2020-02-23 [1] CRAN (R 3.6.1)                   
 dplyr          0.8.5      2020-03-07 [1] CRAN (R 3.6.3)                   
 DT             0.12       2020-02-05 [1] CRAN (R 3.6.3)                   
 e1071          1.7-3      2019-11-26 [1] CRAN (R 3.6.3)                   
 ellipsis       0.3.1      2020-05-15 [1] CRAN (R 3.6.1)                   
 evaluate       0.14       2019-05-28 [1] CRAN (R 3.6.3)                   
 fansi          0.4.1      2020-01-08 [1] CRAN (R 3.6.2)                   
 fastmap        1.0.1      2019-10-08 [1] CRAN (R 3.6.1)                   
 ggplot2        3.3.1      2020-05-28 [1] CRAN (R 3.6.3)                   
 glue           1.4.1      2020-05-13 [1] CRAN (R 3.6.3)                   
 gtable         0.3.0      2019-03-25 [1] CRAN (R 3.5.3)                   
 hms            0.5.3      2020-01-29 [1] Github (tidyverse/hms@1bd14da)   
 htmltools      0.4.0      2019-10-04 [1] CRAN (R 3.6.1)                   
 htmlwidgets    1.5.1      2019-10-08 [1] CRAN (R 3.6.2)                   
 httpuv         1.5.2      2019-09-11 [1] CRAN (R 3.5.2)                   
 httr           1.4.1      2019-08-05 [1] CRAN (R 3.5.3)                   
 jsonify        1.1.1      2020-03-14 [1] CRAN (R 3.6.3)                   
 jsonlite       1.6.1      2020-02-02 [1] CRAN (R 3.6.2)                   
 KernSmooth     2.23-15    2015-06-29 [1] CRAN (R 3.6.1)                   
 knitr          1.28       2020-02-06 [1] CRAN (R 3.6.3)                   
 later          1.0.0      2019-10-04 [1] CRAN (R 3.6.1)                   
 lazyeval       0.2.2      2019-03-15 [1] CRAN (R 3.5.3)                   
 leaflet        2.0.2      2018-08-27 [1] CRAN (R 3.6.1)                   
 lifecycle      0.2.0      2020-03-06 [1] CRAN (R 3.6.3)                   
 magrittr       1.5        2014-11-22 [1] CRAN (R 3.5.1)                   
 mime           0.9        2020-02-04 [1] CRAN (R 3.6.2)                   
 munsell        0.5.0      2018-06-12 [1] CRAN (R 3.5.1)                   
 packrat        0.5.0      2018-11-14 [1] CRAN (R 3.5.3)                   
 pillar         1.4.4      2020-05-05 [1] CRAN (R 3.6.3)                   
 pkgconfig      2.0.3      2019-09-22 [1] CRAN (R 3.6.1)                   
 plotly         4.9.2      2020-02-12 [1] CRAN (R 3.6.3)                   
 promises       1.1.0      2019-10-04 [1] CRAN (R 3.6.1)                   
 purrr          0.3.4      2020-04-17 [1] CRAN (R 3.6.3)                   
 R6             2.4.1      2019-11-12 [1] CRAN (R 3.6.1)                   
 RColorBrewer   1.1-2      2014-12-07 [1] CRAN (R 3.5.0)                   
 Rcpp           1.0.4.6    2020-04-09 [1] CRAN (R 3.6.3)                   
 remotes        2.1.0      2019-06-24 [1] CRAN (R 3.5.3)                   
 rlang          0.4.6      2020-05-02 [1] CRAN (R 3.6.1)                   
 rmarkdown      2.1        2020-01-20 [1] CRAN (R 3.6.3)                   
 RPostgres      1.2.0      2019-12-18 [1] CRAN (R 3.6.1)                   
 rstudioapi     0.11       2020-02-07 [1] CRAN (R 3.6.3)                   
 scales         1.1.1      2020-05-11 [1] CRAN (R 3.6.3)                   
 sessioninfo    1.1.1      2018-11-05 [1] CRAN (R 3.5.3)                   
 sf             0.9-3      2020-05-04 [1] CRAN (R 3.6.3)                   
 shiny          1.4.0.2    2020-03-13 [1] CRAN (R 3.6.3)                   
 shinyjs        1.1        2020-01-13 [1] CRAN (R 3.6.3)                   
 stringi        1.4.6      2020-02-17 [1] CRAN (R 3.6.2)                   
 stringr        1.4.0      2019-02-10 [1] CRAN (R 3.5.2)                   
 tibble         3.0.1      2020-04-20 [1] CRAN (R 3.6.3)                   
 tidyr          1.0.3      2020-05-07 [1] CRAN (R 3.6.3)                   
 tidyselect     1.1.0      2020-05-11 [1] CRAN (R 3.6.3)                   
 timevis        0.5.0.9005 2020-03-24 [1] Github (daattali/timevis@e3e06df)
 tinytex        0.20       2020-02-25 [1] CRAN (R 3.6.3)                   
 units          0.6-6      2020-03-16 [1] CRAN (R 3.6.1)                   
 vctrs          0.3.0      2020-05-11 [1] CRAN (R 3.6.3)                   
 viridisLite    0.3.0      2018-02-01 [1] CRAN (R 3.5.1)                   
 waiter         0.1.0      2020-01-14 [1] CRAN (R 3.6.2)                   
 withr          2.2.0      2020-04-20 [1] CRAN (R 3.6.3)                   
 xfun           0.14       2020-05-20 [1] CRAN (R 3.6.3)                   
 xtable         1.8-4      2019-04-21 [1] CRAN (R 3.5.3)                   
 yaml           2.2.1      2020-02-01 [1] CRAN (R 3.6.2) 
```

</p>
</details>

**Comment by gaborcsardi** [comment] 2020-06-05 07:56
Did you install rtools? https://cran.r-project.org/bin/windows/Rtools/

**Comment by trafficonese** [comment] 2020-06-05 07:59
Yes, `Sys.which("make")` gives me `C:\\Rtools\\bin\\make.exe`

**Comment by gaborcsardi** [comment] 2020-06-05 09:59
Can you install other packages from source, e.g. 
```r
install.packages("glue", type = "source")
```
?

**Comment by trafficonese** [comment] 2020-06-05 10:29
Yes that worked. 

I dont know if it is related, but I also get some other error before `R CMD build` starts:
```
r-lib-processx-2550adc/CODE_OF_CONDUCT.md: Can't create '\\\\?\\C:\\Users\\rn\\AppData\\Local\\Temp\\RtmpQphhV4\\remotes9a05343400\\r-lib-processx-2550adc\\CODE_OF_CONDUCT.md'
tar.exe: Error exit delayed from previous errors.
```

**Comment by gaborcsardi** [comment] 2020-06-05 10:53
Right, the repo has a symlink, `tar.exe` cannot handle that. Current workaround:

```r
Sys.setenv(TAR = "internal")
remotes::install_github("r-lib/processx")
```

You might also need to remove the lock directory.

**Comment by trafficonese** [comment] 2020-06-05 10:59
Still the same error, but some new warning messages at the end.

```
C:/RBuildTools/3.5/mingw_32/bin/gcc  -I"C:/Users/rn/DOCUME~1/R/R-36~1.1/include" -DNDEBUG       -DSTRICT_R_HEADERS   -O3 -Wall  -std=gnu99 -mtune=generic -c init.c -o init.o
In file included from processx-connection.h:24:0,
                 from processx.h:18,
                 from init.c:2:
errors.h:15:24: fatal error: Rinternals.h: No such file or directory
 #include <Rinternals.h>
                        ^
compilation terminated.
make: *** [C:/Users/rn/DOCUME~1/R/R-36~1.1/etc/i386/Makeconf:208: init.o] Error 1
ERROR: compilation failed for package 'processx'
* removing 'C:/Users/rn/Documents/R/R-3.6.1/library/processx'
* restoring previous 'C:/Users/rn/Documents/R/R-3.6.1/library/processx'
Fehler: Failed to install 'processx' from GitHub:
  (konvertiert von Warnung) installation of package ‘C:/Users/rn/AppData/Local/Temp/RtmpQphhV4/file9a028d65c95/processx_3.4.2.9000.tar.gz’ had non-zero exit status
Zusätzlich: Warnmeldungen:
1: In untar2(tarfile, files, list, exdir, restore_times) :
  failed to copy ‘r-lib-processx-2550adc/inst/CODE_OF_CONDUCT.md’ to ‘r-lib-processx-2550adc/CODE_OF_CONDUCT.md’
2: In untar2(tarfile, files, list, exdir, restore_times) :
  skipping pax global extended headers
3: In untar2(tarfile, files, list, exdir, restore_times) :
  skipping pax global extended headers
```

**Comment by gaborcsardi** [comment] 2020-06-05 15:29
Can you pls show all the output, not just parts of it? Thanks. Also, you need to set the `R_REMOTES_NO_ERRORS_FROM_WARNINGS="true"` env var, see https://github.com/r-lib/remotes#environment-variables

**Comment by trafficonese** [comment] 2020-06-05 19:14
Yes of course.
```
> Sys.setenv(TAR = "internal")
> Sys.setenv("R_REMOTES_NO_ERRORS_FROM_WARNINGS" = TRUE)
> remotes::install_github("r-lib/processx")
```

```
Downloading GitHub repo r-lib/processx@master
Running `R CMD build`...
* checking for file 'C:\Users\rn\AppData\Local\Temp\RtmpGaW9L3\remotes3fe839542ba\r-lib-processx-2550adc/DESCRIPTION' ... OK
* preparing 'processx':
* checking DESCRIPTION meta-information ... OK
* cleaning src
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* building 'processx_3.4.2.9000.tar.gz'
* installing *source* package 'processx' ...
** using staged installation
** libs

*** arch - i386
c:/Rtools/mingw_32/bin/gcc  -O3 -Wall  -std=gnu99 -mtune=generic -Wall tools/px.c -o tools/px.exe
c:/Rtools/mingw_32/bin/gcc  -O3 -Wall  -std=gnu99 -mtune=generic -Wall tools/interrupt.c -o tools/interrupt.exe
c:/Rtools/mingw_32/bin/gcc  -O3 -Wall  -std=gnu99 -mtune=generic supervisor/supervisor.c supervisor/utils.c supervisor/windows.c -o supervisor/supervisor.exe
c:/Rtools/mingw_32/bin/gcc  -I"C:/Users/rn/DOCUME~1/R/R-36~1.1/include" -DNDEBUG       -DSTRICT_R_HEADERS   -O3 -Wall  -std=gnu99 -mtune=generic -c init.c -o init.o
In file included from processx-connection.h:24:0,
                 from processx.h:18,
                 from init.c:2:
errors.h:15:24: fatal error: Rinternals.h: No such file or directory
 #include <Rinternals.h>
                        ^
compilation terminated.
make: *** [C:/Users/rn/DOCUME~1/R/R-36~1.1/etc/i386/Makeconf:208: init.o] Error 1
ERROR: compilation failed for package 'processx'
* removing 'C:/Users/rn/Documents/R/R-3.6.1/library/processx'
* restoring previous 'C:/Users/rn/Documents/R/R-3.6.1/library/processx'
Warnmeldungen:
1: In untar2(tarfile, files, list, exdir, restore_times) :
  failed to copy ‘r-lib-processx-2550adc/inst/CODE_OF_CONDUCT.md’ to ‘r-lib-processx-2550adc/CODE_OF_CONDUCT.md’
2: In untar2(tarfile, files, list, exdir, restore_times) :
  skipping pax global extended headers
3: In untar2(tarfile, files, list, exdir, restore_times) :
  skipping pax global extended headers
4: In i.p(...) :
  installation of package ‘C:/Users/rn/AppData/Local/Temp/RtmpGaW9L3/file3fe83d3777fa/processx_3.4.2.9000.tar.gz’ had non-zero exit status


```

**Comment by gaborcsardi** [comment] 2020-06-30 14:48
I can't reproduce this. What's your RStudio version? Does it work from RGui? Can you please run `rstudioapi::buildToolsCheck()` from RStudio and show me the output?

**Comment by trafficonese** [comment] 2020-07-07 07:26
I am using RStudio Version 1.3.952.
It's also not working in RGui.

```
> rstudioapi::buildToolsCheck() 
[1] TRUE
```

**Comment by gaborcsardi** [comment] 2020-07-07 08:45
I just tried this both in Rterm and RStudio, on R 3.6.x, it works fine:

```
Sys.setenv(R_REMOTES_STANDALONE = "true")
Sys.setenv(PATH = paste0("c:\\rtools\\bin;", Sys.getenv("PATH")))
unlink("C:/Users/csard/R/win-library/3.6/00LOCK-processx", recursive = TRUE)
remotes::install_github("r-lib/processx", force = TRUE)
```

(You'd need to modify the `unlink()` line to point to the right lock directory.)

Did you modify your R config? E.g. the Makeconf file? Or set up some environment variables that modify it? 

Does it work for another package from GitHub? E.g. does this work?
```
remotes::install_github("r-lib/ps")
```

Can you try removing rtools and installing it again?

To double check, I just 
1. Removed my user library completely.
1. Installed R 3.6.1 from scratch, with all default settings.
1. Set RStudio (a recent daily build, but I don't think this is essential) to use R 3.6.1.
1. Installed remotes from CRAN
1. Ran the four lines of code above.

It all works fine.

**Comment by trafficonese** [comment] 2020-07-08 12:35
I did not personally modify the R config ot Makeconf. I wouldnt even know where to do that.
I tried out the `renv` package, since then I am seeing some weird behaviour.

Unfortunately it does not work for `r-lib/ps` or `r-spatial/mapview` either.

I removed Rtools and reinstalled it, without success.

**Comment by gaborcsardi** [comment] 2020-07-08 13:03
Right. There is probably some leftover config file from renv that is still active on your system. I suggest you look for `.Rprofile` files in your project directories and remove them. 

You can try to run `.libPaths()` to see which libraries are active, maybe there a leftover library there.

You can also try to delete R and install it from scratch.

**Comment by gaborcsardi** [comment] 2020-07-15 14:11
I am closing this, if you still have issues, maybe try https://community.rstudio.com/ with the `renv` label?

**Closed by gaborcsardi** 2020-07-15 14:11 UTC
Labels: bug, reprex
