### ISSUE TITLE
Terminated processes detected as silent on Ubuntu 16.04

### ISSUE THREAD

**Issue by krlmlr** [r-lib/processx#82] opened 2017-11-08 23:12 UTC
Can't replicate yet, but seems likely given the behavior of revdepcheck.

Reference: https://github.com/r-lib/revdepcheck/issues/117#issuecomment-342984208

**Comment by gaborcsardi** [comment] 2017-11-08 23:14
But this is only with the new processx version, right?

**Comment by krlmlr** [comment] 2017-11-08 23:18
Yes, CRAN version works (but can't do 64 cores :-( ).

**Comment by krlmlr** [comment] 2017-11-08 23:18
Wild guess: Maybe this affects workers that write to stdout and die before their output has been collected?

**Comment by gaborcsardi** [comment] 2017-11-08 23:19
There are explicit test cases for that....

**Comment by gaborcsardi** [comment] 2017-11-08 23:23
Actually, maybe only for reading after termination, but not polling? Anyway, I'll need to try to reproduce this.

**Comment by gaborcsardi** [comment] 2017-11-08 23:45
So, do you know if the same processes are stuck forever, or they are just cleaned up much later?

**Comment by krlmlr** [comment] 2017-11-08 23:50
I think they're cleaned up after the timeout, which I've set to one hour in my tests.

FWIW, one test fails on my server:

```
Failed -------------------------------------------------------------------------
1. Failure: restart (@test-process.R#39) ---------------------------------------
p$is_alive() isn't true.
```

**Comment by gaborcsardi** [comment] 2017-11-08 23:52
Thanks. I meant that maybe they are cleaned up after the (max) 8 minute step of the event loop?

That test case failure is probably not relevant, but what is your platform?

**Comment by gaborcsardi** [comment] 2017-11-08 23:55
OK, I think I got something.

**Comment by krlmlr** [comment] 2017-11-08 23:58
Ubuntu 16.04. The event loop stalls for about 8 seconds for each download, the 8 minutes were a projection for (hypothetical) 64 cores if scheduling each check job takes that long.

**Comment by gaborcsardi** [comment] 2017-11-09 00:32
OK, I believe that it is better now, thanks to e65b331ec627a182585dffc81e50dc7d9586cccd.

Pls also update `revdepcheck`, to get https://github.com/r-lib/revdepcheck/commit/4cc69139d8ef0bb8e6bb412e7c551310d264ec57

We really should write the stdout/stderr to files, because we are not using it until the process is done. The only thing is that `processx` cannot poll if there are no connections. It should be able to `wait()` on multiple processes and return as soon as one is done.

**Comment by krlmlr** [comment] 2017-11-09 00:51
The patches look good, I'll try tomorrow. (The server should get some stuff done first ;-) )

**Comment by krlmlr** [comment] 2017-11-09 15:24
Running now from revdepcheck. It seems that most if not all polling calls reach the timeout of 200 ms, but then in every iteration of the event loop there is an event for every package. I find that unlikely, but detailed debugging output is off now. Another wild guess: Maybe now all workers are marked as "ready", even those that should be "silent"?

**Comment by gaborcsardi** [comment] 2017-11-09 17:02
Yeah, there are two issues, one in `processx`, one in `revdepcheck`. Will fix today, need a break now.

**Comment by gaborcsardi** [comment] 2017-11-09 20:15
OK, the `processx` issue is fixed, the poll does not always wait until the end now, if some processes have buffered output, but others are silent.

**Comment by gaborcsardi** [comment] 2017-11-09 20:30
The reason for all processes being ready is that we are reading complete lines, and polling returns "ready" if any data is available. So we need to just read the non-line-oriented data, really.

I'll do the following:
- redirect stdout to a file, which we read in once the task is done
- read stderr in a non line-oriented way, so we always read in as much data as possible and clear the buffers. To make this fast, we output the data into a file (or rawConnection?) immediately, after reading. This will be tricky to do well, because we either need to keep many connections open, so we can run out of them, or keep opening and closing the file.

**Comment by gaborcsardi** [comment] 2017-11-09 21:36
In the end I chose a different way, but `revdepcheck` should be fixed now as well. It looks much better. I tried on my 4 core macbook with 16 workers, and the main process is no longer the bottleneck. Everything seems much snappier as well, although that could be psychological. :)

**Closed by gaborcsardi** 2017-11-09 21:36 UTC
